### ISSUE TITLE
Models Base User

### ISSUE THREAD

**Issue by victoraugusto6** [rafael-hsm/curso-django#24]
Tente trocar esta linha:
https://github.com/rafael-hsm/curso-django/blob/ace51e984ad8b67b55b340fed6ead012b4862add/pypro/base/models.py#L25
Por:
`extra_fields.setdefault('is_staff', False)`

Tente trocar esta linha:
https://github.com/rafael-hsm/curso-django/blob/ace51e984ad8b67b55b340fed6ead012b4862add/pypro/base/models.py#L28
Por:
`def create_superuser(self, email=None, password=None, **extra_fields):`

**Comment by rafael-hsm** [comment]
Fiz, porém o erro persiste. Não consigo salvar. Entrei até no admin que já foi criado, tentei alterar o primeiro nome e deu o mesmo erro.

**Comment by rafael-hsm** [comment]
Consegui resolver com a ajuda de outros membros no telegram. Bastou excluir a pasta .venv e rodar o pipenv novamente. Obrigado pela ajuda.
